### ISSUE TITLE
Code in repo misses mapTo example

### ISSUE THREAD

**Issue by feoktant** [underscoreio/essential-slick#167]
In 3.3.2 Updating Multiple Fields, there is a code snippet:

```scala
case class NameText(name: String, text: String)
// defined class NameText

val newValue = NameText("Dave", "Now I totally don't trust you.")
// newValue: NameText = NameText(Dave,Now I totally don't trust you.)

messages.
  filter(_.id === 1016L).
  map(m => (m.sender, m.content).mapTo[NameText]).
  update(newValue)
```

However, there is no such code in code:
https://github.com/underscoreio/essential-slick-code/blob/3.2/chapter-03/src/main/scala/main.scala

I am trying to implement this solution, but it does not work. `.mapTo[NameText]` is not compiled.

**Comment by d6y** [comment]
Hi @feoktant  - I've added the example in: https://github.com/underscoreio/essential-slick-code/pull/19

**Comment by feoktant** [comment]
Thank you @d6y !
