### ISSUE TITLE
`url = jdbc:postgresql:chapter-01` for mysql

### ISSUE THREAD

**Issue by xieyuheng** [underscoreio/essential-slick#178]
why the url for mysql is postgresql?

https://github.com/underscoreio/essential-slick/blob/3.3/src/pages/8-databases.md#update-jdbc-references-1

**Comment by d6y** [comment]
That's a mistake. Thanks for reporting it.

**Comment by xieyuheng** [comment]
Thanks for replying.
After this is fixed, I can follow up, and make sure the new config works (for me).

**Comment by xieyuheng** [comment]
with the hope that it will works for more people, if it works for me.

**Comment by d6y** [comment]
I've fixed this now in https://books.underscore.io/essential-slick/essential-slick-3.html#mysql
